### ISSUE TITLE
tgftp and tgftp_log: Additional log file attributes.

### ISSUE THREAD

**Issue by fr4nk5ch31n3r** [fr4nk5ch31n3r/tgftp#2]
To allow reproduction of performance numbers determined with `tgftp`, it should also log the size of the transferred data set (e.g. `GSIFTP_TRANSFER_SIZE`). In addition it could be even more helpful to store the whole data set as transfer list (e.g. `GSIFTP_TRANSFER_LIST` or `GSIFTP_TRANSFER_DATA_SET`) inside of the `tgftp` log file. Also currently missing is the original tgftp command (e.g. `TGFTP_COMMAND`) used for a test.

`tgftp_log` should be enhanced to support extraction of the new attributes.

**Comment by fscheiner** [comment]
Fixed by 48c489ec2d530abb276b04c974c4498c39c2e4f9, b05c2806224a98c853f15792cc4bdf5a1267ef26 and 3ffe94b543a0a3e806e353398116557612f73dce.
